[package]
name = "frame-editor"
version = "0.1.0"
edition = "2024"

[dependencies]

image = { version = "0.25", default-features = false, features = ["png"] }

frame-engine = { path = "../frame-engine" }
winit = "0.30"
softbuffer = "0.4"
wgpu = "29.0.3"
pollster = "0.4.0"
bytemuck = { version = "1", features = ["derive"] }
glam = "0.30"
egui = "0.35"
egui-winit = "0.35"
egui-wgpu = "0.35"
